# Site settings
title: QuokkaLight - French CTF Team
email: quokkalight@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Here you'll find our writeups and info about our projects. :)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://quokkalight.github.io" # the base hostname & protocol for your site
twitter_username: Quokka_Light
github_username:  QuokkaLight

# Build settings
markdown: kramdown
